### ISSUE TITLE
Info.plist is missing NS*UsageDescription

### ISSUE THREAD

**Issue by KishanBagaria** [warpdotdev/Warp#1183]
`cat /Applications/iTerm.app/Contents/Info.plist|plutil -p -|grep UsageDesc` :

```
  "NSAppleEventsUsageDescription" => "An application in iTerm2 wants to use AppleScript."
  "NSBluetoothAlwaysUsageDescription" => "An application in iTerm2 wants to use Bluetooth."
  "NSCalendarsUsageDescription" => "An application in iTerm2 wants to use Calendar data."
  "NSCameraUsageDescription" => "An application in iTerm2 wants to use the camera."
  "NSContactsUsageDescription" => "An application in iTerm2 wants to use your contacts."
  "NSLocationAlwaysUsageDescription" => "An application in iTerm2 wants to use your location information, even in the background."
  "NSLocationUsageDescription" => "An application in iTerm2 wants to use your location information."
  "NSLocationWhenInUseUsageDescription" => "An application in iTerm2 wants to use your location information while active."
  "NSMicrophoneUsageDescription" => "An application in iTerm2 wants to use your microphone."
  "NSRemindersUsageDescription" => "An application in iTerm2 wants to use your reminders."
  "NSSpeechRecognitionUsageDescription" => "An application in iTerm2 wants to use speech recognition."
  "NSSystemAdministrationUsageDescription" => "The operation being performed by a program in iTerm2 requires elevated permission."
```

Warp.app doesn't have any of these keys so apps launched with Warp cannot request many of the above permissions. Notably, the default Terminal.app doesn't have these keys either but apps are able to request those permissions.

### Operating System

MacOS

### OS Version

12.3.1

**Comment by kevinyang372** [comment]
This issue will be fixed in the next release!

**Comment by kevinyang372** [comment]
Closing this as this should be fixed in the latest version of Warp

**Comment by jerryccan** [comment]
the core issue persists in the latest version of Warp.app (v0.2025.04.16.08.11.stable_02);;macOS(15.4 (24E248))
