### ISSUE TITLE
Keyboard shortcut regression | "quake mode"/hotkey window

### ISSUE THREAD

**Issue by arturkot** [warpdotdev/Warp#1232]
### Describe the bug

```text
`Shift + Esc` can't activate hotkey window anymore. It used to work in the previous version (or one of the previous versions) of Warp.
```

### To Reproduce

1. Open options (`CMD + ,`).
2. Navigate to "features".
3. Assign new keyboard shortcut in "Hotkey Window" -> "Keybinding": `Shift + Esc`.
4. Attempt to use the key combination to activate hotkey window—it shouldn't work.

* Tweaking settings like "pin to top" or screen selection doesn't help.
* Restarting Warp doesn't fix the issue.
* Other keyboard shortcuts like `Cmd + Shift + P` work.

### Expected behaviour

```text
`Shift + Esc` shortcut should be able activate the hotkey window.
```

### Screenshots

![CleanShot 2022-04-29 at 08 36 04@2x](https://user-images.githubusercontent.com/1224792/165895613-bf046bd1-81fc-460d-a1e2-904659ccee9a.png)

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
* Warp version: `v0.2022.04.25.09.59 stable_03`
* Two displays setup (MBP + external display).
```

**Comment by ooopscc** [comment]
same here

**Comment by shnigi** [comment]
Same, I had f8 as hotkey. It worked in previous version but stopped working after I updated 15minutes ago.

**Comment by ZzqiZQute** [comment]
Same issue.

**Comment by ooopscc** [comment]
is there a hotfix working in progress?

**Comment by kevinyang372** [comment]
This should be fixed in the latest release!

**Comment by terrymunro** [comment]
Confirmed, fixed for me! Thank you!

**Comment by ooopscc** [comment]
@kevinyang372 not working for me. Tried Option+space, F2.

**Comment by arturkot** [comment]
Fixed in `v0.2022.05.02.09.00. stable_01`, i.e. the latest current Warp version for me.

**Comment by ooopscc** [comment]
For those whose new version hotkey still not working, try to uninstall and reinstall. Maybe there is some cache issue here.

**Comment by oay-nj** [comment]
> , try to unins

this worked for me
