### ISSUE TITLE
Long command output is trimmed

### ISSUE THREAD

**Issue by waldekmastykarz** [warpdotdev/warp#134]
**Describe the bug**
I've just noticed that long command output (~8000 lines, where each line is a unit test that's been executed) is trimmed. The beginning of the output is missing in the block. Not sure if this behavior is intentional or not, but it would be helpful if there was a setting that allows unlimited output.

**To Reproduce**
1. Clone https://github.com/pnp/cli-microsoft365
2. Restore deps (`npm i`)
3. Build (`npm run build`)
4. Run tests (`npm test`)
5. Notice that the beginning of the output is trimmed (output starts mid-test suite)

**Expected behavior**
Full command output visible in the terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/11164679/130236522-8c865d64-3879-43ff-80a5-c85ff5d0e30e.png)

**Desktop (please complete the following information):**
 - OS Version: macOS 11.5.2

**Additional context**
n/a

**Comment by gagata** [comment]
This was fixed in previous releases, closing! :)

**Comment by rburgst** [comment]
@gagata I still have this problem with my version that I downloaded yesterday. Just cat any large file and it will trim the output 
```
cat very-large-file.es.js
]=M,P[E[_$_f545[912]][_$_f545[944]]]=k,P[E[_$_f545[912]][_$_f545[942]]]=C,P))}function _0x5D83(l,o,r){function u(q,L){return T(T({},q),{isRendererStalled:L[_$_f545[1407]]})}function f(){function q(L){for(var x,F=1,U=arguments[_$_f545[272]];F<U;F++){x=arguments[F];for(var B in x)Object[_$_f545[432]][_$_f545[431]][_$_f545[430]](x,B)&&(L[B]=x[B])}return L}return T=Object[_$_f545[791]]||q,T[_$_f545[528]](this,arguments)}function b(q,L,x){if(x||arguments[_$_f545[272]]===2)for(var F,U=0,B=L[_$_f545[272]];U<B;U++)!F&&U in L||(F||(F=Array[_$_f545[432]][_$_f545[487]][_$_f545[430]](L,0,U)),F[U]=L[U]);return q[_$_f545[421]](F||Array[_$_f545[432]][_$_f545[487]][_$_f545[430]](L))}function A(q,L){
...
```

**Comment by rburgst** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/22971/151110942-9754a7bd-19af-42c2-a39c-9467a37829d5.png">
