### ISSUE TITLE
Autocompletion for `git checkout`  adds a "-" instead of showing local branch names

### ISSUE THREAD

**Issue by marcellus-somo** [warpdotdev/Warp#1403]
### Describe the bug

```text
Pressing TAB after `git checkout ` adds a "-" to make it `git checkout -` instead of autocompleting branches.
```

### To Reproduce

Steps to reproduce:
1.  `cd` to a folder containing a git repo
2. Type `git checkout `
3. Press TAB

### Expected behaviour

```text
A menu showing all of the local branches, as described here: https://docs.warp.dev/features/completions
```

### Operating System

MacOS

### OS Version

12.4

### Shell Version

5.8.1

**Comment by ruedigerfranke** [comment]
+1

**Comment by elviskahoro** [comment]
This should be fixed! Please comment if not!

**Comment by marcellus-somo** [comment]
Just updated to v0.2022.07.04.09.08.stable_02 and unfortunately I'm still seeing this bug

**Comment by Nauxscript** [comment]
in v0.2022.07.11.09.11.stable_00, I input `git checkout ` and press tab, its only show tht opions of git, not the local branches

**Comment by marcellus-somo** [comment]
> Just updated to v0.2022.07.04.09.08.stable_02 and unfortunately I'm still seeing this bug

@elviskahoro

**Comment by elviskahoro** [comment]
@marcellus-somo no problem! thanks for commenting

**Comment by elviskahoro** [comment]
It's working for me, so going to close for now. I'll reopen if you're still seeing it on your end @marcellus-somo @Nauxscript
