### ISSUE TITLE
AI Command search returns "An error occurred"

### ISSUE THREAD

**Issue by PsySolix** [warpdotdev/Warp#1531]
### Describe the bug

```text
So suddenly (some days now) the AI search stopped working. 
I reinstalled WARP and verified if I have latest. 

I do have internet and tried different AI searched: 
1) delete git branch
2) remove docker images by name

Tried to find any related issue here, but found none.. So not sure why it maybe is only occuring on my side? 

Thanks in advance!
```

### To Reproduce

Steps to reproduce:
1. Open warp
2. Do any AI command search
3. Immediatly returns "An error occurred while trying to generate a command. Please try again."

### Expected behaviour

```text
Previously it just returned a proper cmd to run :)
```

### Screenshots

![image](https://user-images.githubusercontent.com/6713256/174791600-77017320-0883-490a-b53b-ed1b7644b67a.png)

### Operating System

MacOS

### OS Version

12.3.1 (21E258)

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.13.09.15.stable_01

**Comment by alokedesai** [comment]
Thank you for flagging! I'm actually working on fixing this change right now :) It should be released in next week's release on Wednesday. 

Happy to send over instructions for a short-term fix for this if you'd like to fix  this yourself in the meantime

**Comment by PsySolix** [comment]
@alokedesai No problem! Sorry for the late reaction, will the update release tomorrow/thursday/..? If not then maybe the short-term fix would be awesome :D But if the update schedule is on track, I can wait a few days tho :D 

Thanks in advance!

**Comment by elviskahoro** [comment]
Should be fixed!

**Comment by alokedesai** [comment]
Reopening--this isn't fixed yet but will be tomorrow when the release goes out. I'll make sure to close it out once that happens :)

**Comment by warpdotdev-dx** [comment]
Thanks aloke

**Comment by PsySolix** [comment]
Perfect is completely fixed with the update <3 Thanks!
