### ISSUE TITLE
Long running Gradle command output is cut off

### ISSUE THREAD

**Issue by marukami** [warpdotdev/Warp#2556]
### Describe the bug

Long-running Gradle commands output is cut off. You can briefly see the last few lines of the command output before it's seemly trimmed down. 

### To Reproduce

Using this Android project https://github.com/android/nowinandroid and running
```sh
./gradlew clean assembleDebug --no-build-cache
```

### Expected behaviour

The end of the command output is not cut off.

### Screenshots

Long-running Gradle command
<img width="965" alt="long-command-cut-short" src="https://user-images.githubusercontent.com/1644094/214766335-f7469f41-ba36-440c-bec6-82df7e1f32cd.png">

Run the same Gradle command faster; (By enabling build caching)
<img width="965" alt="short-command-working" src="https://user-images.githubusercontent.com/1644094/214766354-2f6e9400-995d-4462-b3a0-a3a9d3972593.png">

### Operating System

MacOS

### OS Version

12.6.2 

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.01.17.08.03.stable_01

### Additional context

I did find #1963 when searching for an existing issue. I found the build from this comment https://github.com/warpdotdev/Warp/issues/1963#issuecomment-1282364860 did not seem to have the problem. 

Limiting the worker count to 1 fixes it. This has the downside of removing parallelism in the Build.
```sh
./gradlew clean assembleDebug --no-build-cache -Dorg.gradle.workers.max=1
``` 

Side by side with 1 and 10 workers
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/1644094/214774957-73078e07-6856-4f7b-b874-6fb27f55bfc4.png">

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting @marukami sorry to hear about this issue. I'll bring up with the team and we'll post any updates here.

**Comment by vorporeal** [comment]
Hey @marukami, can you confirm that this issue only occurs in Warp and doesn't happen on other terminals (e.g.: iTerm or Terminal.app)?

**Comment by marukami** [comment]
Correct. iTerm2 and Terminal.app do not have this issue.

**Comment by gabrielittner** [comment]
I'm seeing the same and I think it only started happening in the last few weeks or at the very least only started happening regularly since then. It used to work correctly

**Comment by ychescale9** [comment]
Same here, I've had to stop using warp for Gradle builds for the last 1-2 months because of this.

**Comment by mschmnet** [comment]
Also happening to me.

**Comment by dannyneira** [comment]
Hi all! this has been resolved in the most recent version of Warp. Please update and let us know.

**Comment by bbcbreno** [comment]
@dannyneira I still have this problem. In fact, it took me a while to realize that the problem was the cut output.
Sometimes I need to run a giant test and I lose more than half of the output. I don't have this problem on other terminals

Warp version: v0.2024.11.05.08.02.stable_04
platform: macOS 14.1.1
