### ISSUE TITLE
Missing formatting from Jest

### ISSUE THREAD

**Issue by dallonf** [warpdotdev/Warp#289]
### Describe the bug

```shell
In Jest (and presumably other terminal tools), much of the styling simply does not appear in Warp.
```

### To Reproduce

Steps to reproduce:
1. Open a JavaScript project with Jest tests (such as https://github.com/remix-run/react-router/tree/main/packages/react-router)
2. Make sure a couple of the assertions are failing to get some extra output
3. Run `npx jest --watchAll` in the project directory
4. Compare the output to another terminal

### Expected behaviour

```shell
Styling should be equivalent between Warp and other terminals
```

### Screenshots

In iTerm:

![image](https://user-images.githubusercontent.com/346300/138116269-61348aa1-dc98-46cf-b1fd-d666ab1ebd09.png)

in Terminal (with a light theme):

![image](https://user-images.githubusercontent.com/346300/138117176-a3d77f50-2a52-418f-9535-ab123f3e0b7f.png)

In Warp:
![image](https://user-images.githubusercontent.com/346300/138117207-f03f5ebc-210a-49fc-b98e-2af8f49c7180.png)

In particular, notice:
* Checkmarks and "x"s before each test
* Text colors: gray, light blue, dark green, dark yellow
* Yellow is so desaturated that it's impossible to distinguish from white

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
@dallonf we added emojis! They should be working in jest. Did that fix the formatting issues on your end?

**Comment by dallonf** [comment]
The emojis help a lot! 🎉  But the text color issues are still the same.

**Comment by elviskahoro** [comment]
Are the colors off if you use a different theme too?
Suppose you used solarized in your normal terminal and Warp? Are they both still off?

**Comment by dallonf** [comment]
Here are both Warp (left) and iTerm2 (right) set to Solarized Dark:

![image](https://user-images.githubusercontent.com/346300/144649724-b2651f5d-6f0c-4ac5-9072-3abb6d21df11.png)

Interestingly, Warp has some formatting that iTerm2 doesn't (like how "2 snapshots obsolete" is in yellow), but in iTerm, the difference between white and gray is used to highlight certain text and make it easier to read. A more prominent example:

![image](https://user-images.githubusercontent.com/346300/144650149-4cca5058-c890-4887-bc1e-8005f6600d77.png)

**Comment by bkbooth** [comment]
Not sure if this is related, I have a problem with a bunch of CLI tools that colour their output, but Jest in particular when using the "Light" theme (or any of the dark on light themes). I thought it must have been conflicting with my oh-my-zsh theme initially, but even disabling that I have this problem:

![Screen Shot 2022-01-21 at 10 21 29 am](https://user-images.githubusercontent.com/634656/150437909-f63d33c0-bd36-49ad-9352-9903488088a4.png)

The same output renders fine in any of the light on dark themes, although the "white" text colour doesn't appear to change despite the theme.

**Comment by dallonf** [comment]
I've switched to Windows-only for the time being, so I'm not able to check.

**Comment by bkbooth** [comment]
@elviskahoro yep, looks like it's fixed now for me 🙌 Not sure how long it's been fixed for, I've been staying away from light themes, but it looks like they're fine to use now.

![Screen Shot 2022-07-08 at 9 24 14 am](https://user-images.githubusercontent.com/634656/177894949-e15f80c8-8b77-44cb-9852-c2af8728d284.png)

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
