### ISSUE TITLE
Sticky header overlaps pager text

### ISSUE THREAD

**Issue by pswaminathan** [warpdotdev/Warp#2915]
### Describe the bug

The sticky header overlaps pager text. The screenshot example might be the most helpful. In this case, I have a file `example.txt` that just has the line number on each line. If I `less example.txt`, the sticky header covers up the first three lines. This affects anything that uses a pager, e.g. `git log`.

### To Reproduce

1. Download [example.txt](https://github.com/warpdotdev/Warp/files/11191468/example.txt)
2. Open window with height small enough so that fewer than 109 lines are visible
3. Run `less example.txt` 

### Expected behavior

I expect to see the sticky header at the top, _followed by_ line 1. Instead I see the first three lines being cut off by the stick header. My recollection is that this is a regression; I used to find `git log` readable and now it is much less usable.

### Screenshots

<img width="1624" alt="Screenshot 2023-04-10 at 10 22 26 AM" src="https://user-images.githubusercontent.com/2104106/230932280-3939dfc4-2de7-47fd-b141-fefaccca5d77.png">

### Operating System

MacOS

### OS Version

13.3.1 (22E261)

### Shell Version

zsh 5.9

### Warp Version

v0.2023.04.04.08.03.stable_01

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zackbrown** [comment]
Same here!  Unhappy with this regression — it's the opposite of "stays out of my way," which is my number one requirement for a terminal app.  This regression breaks very fundamental flows, for example, `git log`.  

See screenshot:  cannot see the top commit info when I run `git log` (can scroll up manually to "fix", but only if I use mouse scroll wheel, and not by using arrow keys.)

Have tried all three of the new `input position` settings and none fixes this regression.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/2100885/230949867-dca4448a-85ec-4296-aaa8-877fed8f4812.png">

**Comment by zackbrown** [comment]
Found a way to fix this by disabling `Settings > Features > Show Sticky Command Header`: 
<img width="491" alt="image" src="https://user-images.githubusercontent.com/2100885/230951327-d8ea7a91-b954-4127-b5cb-e8b1925eb183.png">

Read more at: https://docs.warp.dev/features/blocks/sticky-command-header

Not sure if this should be considered a feature or a bug.  As a user, having this suddenly appear after an update was an anti-feature at best, but probably wouldn't be an issue if `git log` just showed the output it was supposed to show.

**Comment by pswaminathan** [comment]
@zackbrown appreciate the work-around! FWIW I don't think disabling the header is a fix, per se. It is a work-around. Which is nice! But the sticky header is nice, and it would be nice if the pager worked with it, I don't want people to read your message and close this out 🙂. My recollection is that the two _did_ work together before, but I may be misremembering that.

**Comment by dannyneira** [comment]
Hey folks, sorry about this issue, it mainly appears to be happening when less if called via `git log`, not directly with `less example.txt`. 

We recommend disabling the Sticky command header as a workaround, [like @zackbrown mentioned above](https://github.com/warpdotdev/Warp/issues/2915#issuecomment-1502060753). 

We're pushing a fix out most likely in this week's Thursday release and will post any updates here.

**Comment by alokedesai** [comment]
Hey folks very sorry for the breakage. Just an update here: a fix was merged last night, which means it will be part of this week's release on Thursday. 

Thank you again for your patience--we'll close this issue as soon the release goes out.

**Comment by pswaminathan** [comment]
Thank you both for the quick responses and fix!

**Comment by alokedesai** [comment]
Hey everyone, this should now be released so i'm going to close out. Please let me know if you are still experiencing issues with this!

**Comment by patbl** [comment]
Sure, here's a video: https://www.awesomescreenshot.com/video/16525037?key=39d6730f2d15b5e7288fa608a1bb1bf4

My Warp version is v0.2023.04.11.08.03.stable_00

**Comment by alokedesai** [comment]
@patbl We are actively working on f

**Comment by wademaxfield** [comment]
I'm also seeing this issue with v0.2023.05.02.08.03.stable_00 and running `top`

**Comment by vogler** [comment]
Still breaks my `git log` with [delta](https://github.com/dandavison/delta) as a pager. Once I scroll one line down, the header will overlap the beginning even when scrolling back up.
v0.2023.05.09.08.03.stable_01

**Comment by dannyneira** [comment]
Hey Folks, we've made some recent changes that should address this issue. Please update to the latest Warp `v0.2023.05.23.08.05.stable_00` and confirm the issue is resolved.

**Comment by vogler** [comment]
Says v0.2023.05.23.08.05.stable_00 is up to date, issue is not resolved.

**Comment by alokedesai** [comment]
Hey @vogler, the issue will be fixed in the release that goes out today (`v0.2023.05.30.08.03.stable_01`). It's not yet released, but should be very soon. Thanks for your patience!

**Comment by dannyneira** [comment]
Hi all, Warp release `v0.2023.05.30.08.03.stable_02` has addressed this issue, closing as resolved, but please feel free to let us know if the issue persists.

**Comment by dannyneira** [comment]
It appears this issue is still present with `ipython` as per #3171, we'll continue to track the progress on that issue for ipython specifically.

**Comment by vogler** [comment]
Not resolved with `delta` for me:

https://github.com/warpdotdev/Warp/assets/493741/ce6c10fc-e505-4fd7-b882-68a7f089ad22

Also seems like you introduced a regression on key repeat. Can't hold `j` to scroll the output anymore - also for `man` (`nvim` works).

**Comment by dannyneira** [comment]
hey @vogler Sorry to hear about this, could you please open a new bug report for this issue, We'll have to look into this as a possible regression.

**Comment by joonassandell** [comment]
Howdy, when the sticky header is active and I run Vite dev server (`vite`) the log stays hidden under the header. This can be prevented by running `vite --clearScreen false` or simply by hiding the sticky header. I wanted to mention this because I was pretty confused initially when I couldn't see any logs.

**Comment by patbl** [comment]
This is still an issue for me with any Git commands that use a pager, for example `git -c core.pager=less log`:

## before pressing <kbd>Return</kbd>
<img width="1904" alt="image" src="https://github.com/warpdotdev/Warp/assets/1735266/2c5f0aff-8baa-4a18-9298-1d16e8cff27d">

## after pressing <kbd>Return</kbd>
<img width="1904" alt="image" src="https://github.com/warpdotdev/Warp/assets/1735266/d54cbd87-ba5c-453d-8557-7c954accef50">

But it's a smaller issue than it was before—the command is partially visible, whereas before the fix, the first several lines were obscured.

**Comment by msc-consults** [comment]
I also experience this issue but when SSH'ing into a Kubernetes pod/container using K9s
See my repeatable steps below:

1. SSH into Pod -> container using K9s
2. establish a psql sessions with a postgres database instances from the container
3. ctrl+d to leave the psql session
4. ctrl+d once more to the SSH session with the container
5. SSH back into the Pod -> container

When you do this the command sticky header blocks the bash prompt of the container.
You can only see the shell prompt if you hit the return key a few times to move the prompt further down the screen

![image](https://github.com/warpdotdev/Warp/assets/25661431/7ed868ef-1d29-4d02-85fb-b9a4b545cb9d)
