### ISSUE TITLE
SSH on one tab takes focus from other tabs

### ISSUE THREAD

**Issue by garythung** [warpdotdev/Warp#3265]
### Discord username (optional)

garythung

### Describe the bug

Making an ssh connection will steal focus from other tabs/panes when the ssh successfully connects.

### To reproduce

Multi tab experience

1. Open Warp
2. Open two tabs
3. In tab 1, ssh into a server
4. Quickly switch to tab 2
5. After a couple of seconds, ssh is successful and the cursor loses focus on tab 2

For multi pane, this happens as well but it actually switches the focus over to the other pane.

1. Open Warp
2. CMD+D to open a split pane
3. In pane 1, ssh into a server
4. Quickly switch active pane to pane 2
5. Focus will go back to pane 1 when ssh is successful

### Expected behavior

I don't think activity in other tabs should interrupt current focus.

### Operating system

MacOS

### Operating system and version

Ventura 13.4

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, sorry about the blocker. Could you please provide a video of the issue, I can't quite reproduce this on my end by running `sleep 10 ; ssh user@ip` and then opening a new tab.

Also, assuming you are using zsh, check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run echo 'ZDOTDIR=/' > ~/.zshenv
This forces Zsh to run with zero configs.

**Comment by Eazash** [comment]
I've noticed that this bug seems to be gone on the current stable release (v0.2023.07.04.08.03.stable_02)

**Comment by camilovietnam** [comment]
I have the same issue. I need to connect to multiple servers so I open a terminal, run the SSH command, then open a new tab and while I'm typing the command, the cursor will be taken from the active tab as soon as the ssh is connected in the other tab. I wish this didn't happen.

**Comment by dougfarnes** [comment]
Same issue here, thank you for reporting, am on v0.2023.08.22.08.03.stable_00 right now.

**Comment by its-luca** [comment]
I am on version `v0.2023.09.26.08.09.stable_00` and have the same issue

**Comment by Shankar1598** [comment]
This is still happening. In the latest release: `v0.2024.02.13.08.02.stable_00`

**Comment by alzrck** [comment]
still occurring in v0.2024.06.25.08.02.stable_01

**Comment by Moonrag** [comment]
up, v0.2025.03.12.08.02.stable_03

**Comment by dougfarnes** [comment]
@Moonrag I was about to reply saying +1, as I've had this problem forever, and as recently as a week ago I think. However, it looks like it's fixed in v0.2025.03.26.08.10.stable_02 (on Sequoia 15.3.2).

I just tested and it doesn't steal focus anymore.

**Comment by Moonrag** [comment]
@dougfarnes just checked, v0.2025.03.26.08.10.stable_02, Sequoia 15.3.2, bug still exists for me :/

https://github.com/user-attachments/assets/15679dde-9818-40b0-8113-ef6f62dde792

**Comment by camilovietnam** [comment]
Just migrated to a new computer and installed the latest version of Warp (v0.2025.12.17.17.17.stable_02) and the problem is happening again. Funny thing is, I have the same version in another laptop and the focus does not get stolen from one pane to another. I will check if there's a setting that is preventing this problem

**Comment by jumploops** [comment]
Repeating from #13123: 
  
I've noticed that this always happens when connecting to a remote via SSH, not sure if it happens otherwise. 
  
Focus is lost on all tabs. 
  
Repro:
- Tab 1: SSH into remote
- Switch tabs immediately
- Tab 2: Focused, until SSH connects, then focus lost
- Need to click input box again to refocus
  
 Warp version: `v0.2026.07.29.09.05.stable_02`

> My current project has me SSHing into a few machines, and this really breaks the experience for me. Thinking about switching back to Ghostty, even if requires more upfront config. This feels like the level of polish that, if this is broken, what else can't I control? 
> More random feedback: tab complete will sometimes send me into "agent" mode and I have no idea why.
