### ISSUE TITLE
Core: colors don't seem to work

### ISSUE THREAD

**Issue by madisp** [warpdotdev/Warp#367]
### Describe the bug

```shell
I use [doge](https://github.com/thiderman/doge) as a welcome screen in my terminal, for some reason the rendering is really off with warp. Screenshots with iTerm and Warp attached.
```

### To Reproduce

Steps to reproduce:
1. Install [doge](https://github.com/thiderman/doge)
2. Run `doge` in the terminal

### Expected behaviour

```shell
A nicely rendered dog
```

### Screenshots

warp.dev:

<img width="847" alt="Screen Shot 2021-11-06 at 20 14 01" src="https://user-images.githubusercontent.com/1147723/140619711-df0f89a9-9d16-4c14-93dd-c775bf5de183.png">

iterm:

<img width="602" alt="Screen Shot 2021-11-06 at 20 13 24" src="https://user-images.githubusercontent.com/1147723/140619698-1c7bb961-a7d6-4593-8ea1-d855985ad5fa.png">

### Operating System

MacOS

### OS Version

11.6.1

**Comment by elviskahoro** [comment]
Should be fixed! please reopen if it's not working.

**Comment by madisp** [comment]
It's still happening, but I think I can't reopen issues if a repo collaborator has closed them.

<img width="1136" alt="Screen Shot 2021-12-08 at 20 15 46" src="https://user-images.githubusercontent.com/1147723/145261904-50018155-fe83-4921-bd2d-68eb15918d65.png">

**Comment by madisp** [comment]
resizing the terminal sort of fixes it, it looks as if the upper part of the terminal works ok?

https://user-images.githubusercontent.com/1147723/145283495-53c9b973-d456-4676-b4b6-9898832faf29.mp4

my machine is a Mid-2014 macbook pro with intel iris graphics running big sur

**Comment by madisp** [comment]
After upgrading to `v0.2021.12.06.19.09.stable_00` more of the image is correct, but the bottom is still broken. The "breaking point" seems to be the same, regardless of terminal size.

(Note that there are slight rendering differences between the video above and this screenshot due to different font being used).

<img width="1045" alt="Screen Shot 2021-12-09 at 12 40 33" src="https://user-images.githubusercontent.com/1147723/145381680-b621a330-20f8-4d5e-97b6-22be09b38425.png">

**Comment by elviskahoro** [comment]
@madisp is this still happening to you?
<img width="1008" alt="Screen Shot 2022-03-16 at 17 09 23" src="https://user-images.githubusercontent.com/29553206/158691575-83e7e67f-04bd-4a35-93b1-f165c4bbe471.png">

**Comment by madisp** [comment]
@elviskahoro still broken on `v0.2022.03.14.08.49.stable_00`, should that build already include the fix?

**Comment by elviskahoro** [comment]
@madisp idk how i missed this. hopefully it's working for yuh!

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
