### ISSUE TITLE
Linux: middle click paste isn't working

### ISSUE THREAD

**Issue by guy-borderless** [warpdotdev/Warp#4329]
### Describe the bug

When pressing the middle mouse button on top of the warp terminal no paste action of the selected text is performed. This is a convention and default behavior in linux. 

### To reproduce

select text in an app other than warp
middle click on top of warp

### Expected behavior

selected text is pasted

### Operating system

Linux

### Operating system and version

Manjaro Gnome

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by paddylandau** [comment]
I've just started using Warp in Linux (it's a lovely terminal emulator), and I've been finding this quite frustrating!

It's both ways: Select text in another app and middle-click in Warp, or select text in Warp and middle-click in another app. Also, this doesn't work: select text in Warp and middle-click in Warp.

**Comment by guy-borderless** [comment]
> I've just started using Warp in Linux (it's a lovely terminal emulator), and I've been finding this quite frustrating!
> 
> It's both ways: Select text in another app and middle-click in Warp, or select text in Warp and middle-click in another app. Also, this doesn't work: select text in Warp and middle-click in Warp.

I've opened one for that: #4328

**Comment by igorsantos07** [comment]
Looks like a dupe of #2853

**Comment by ZsBT** [comment]
+1 for this. This is implemented in most of the linux terminals, therefore Warp for Linux users highly depend on this.

**Comment by alokedesai** [comment]
Hi all, thanks for you your patience here. We are currently looking into this and hope to have this fixed soon.

**Comment by Yummy-Yums** [comment]
Hey @alokedesai will the fix come with a paste action in the menu ( screenshot below ) ? or a Ctrl + Shift + V at least? if not can you add it? Thanks

![image](https://github.com/warpdotdev/Warp/assets/77977520/0f16506e-6d53-41e3-98f6-40f26000bd1c)

**Comment by alokedesai** [comment]
@Yummy-Yums Mind filing another issue for this? I'd like to keep this issue focused on supporting middle click paste. Thank you!

**Comment by jeremyronking** [comment]
Please don't limit this feature to be on Linux only.  Us Mac users also use middle click paste in our terminals.

**Comment by rlinq** [comment]
For Mac users make it a configurable option, to also support paste on right click.

I'm daily connecting to remote systems, running windows VDI and use terminal programs like WinSSHterm. There I can enjoy the feature of copy on select and paste with my Mac mouse right button.

It's so efficient, I've almost given up on this request in WARP, now when it's looked at, please make it configurable with both copy on select and paste with right button.

Thanks for all hard work!

See this post as a discussion I found about copy/paste behaviour with mouse only.

https://apple.stackexchange.com/questions/14163/how-to-configure-terminal-to-be-putty-like-when-it-comes-to-copy-paste-with-mo/14165#14165

in iTerm2 go to "Options -> General -> install test-release updates (or something like this)", check for updates, install last test-release (1.0.0.20130622 by now) and get new option "Right button single click -> Paste from Selection" in Options -> General -> Pointer.

**Comment by ablundgren** [comment]
The original poster said this did not prevent them from using warp.

It does block mine. It's a blocker for me.

**Comment by SilentGlasses** [comment]
Blocker for me too..  I have been using on Mac for a bit and was super excited for Linux as that is my main personal OS but I can't really use it if it does not accept middle click paste. Why? Two reasons:

1. I have to type out the entire thing I need to paste
2. It takes extra key strokes to paste other wise... `ctrl`+`shift`+`v`

**Comment by abhishekp106** [comment]
Hey everyone! This issue will be fixed in the next release! Middle-click paste will now work for users on both Linux and macOS. Thanks for taking the time to file this issue and upvote/comment.

If your system has a primary clipboard, then Warp will use that. For macOS and older versions of Wayland that don't have a primary clipboard, Warp will use the default clipboard. If it doesn't work, double check that the "Copy on select" setting is enabled (this should be enabled by default). You can check this by visiting `Settings > Features > General > Copy on select` and making sure the toggle is on.

**Comment by abhishekp106** [comment]
@rlinq Do you mind filing a separate issue for supporting right-click to paste? We want to keep this issue focused on middle-click. Thanks so much!

**Comment by paddylandau** [comment]
> @abhishekp106 is it implemented that selected text is copied to the primary clipboard as well? This is important for middle-click pasting in other apps as well as other things.

This report is for Linux. Middle-click merely copies the currently-selected text to the target; it doesn't, and shouldn't, place it into the clipboard. (If you need that sort of functionality, you need a desktop environment that supports that or, for something like GNOME, a suitable extension.) It should place selected text into the clipboard only on an explicit copy (Shift+Ctrl+C or right-click+Copy).

**Comment by poldap** [comment]
What version is supposed to fix this? v0.2024.03.05.08.02.stable_01 here and this is not working.

**Comment by alokedesai** [comment]
Hey @poldap, this will be available in the next release of Warp, which will be released tomorrow.

**Comment by guy-borderless** [comment]
> > @abhishekp106 is it implemented that selected text is copied to the primary clipboard as well? This is important for middle-click pasting in other apps as well as other things.
> 
> This report is for Linux. Middle-click merely copies the currently-selected text to the target; it doesn't, and shouldn't, place it into the clipboard. (If you need that sort of functionality, you need a desktop environment that supports that or, for something like GNOME, a suitable extension.) It should place selected text into the clipboard only on an explicit copy (Shift+Ctrl+C or right-click+Copy).

@paddylandau , we were referring to something else. the primary clipboard is used for selected text, not copied text. when you select text and copy it the primary and the secondary (used for copy paste) clipboards are equal. middle click however uses the primary clipboard

**Comment by dannyneira** [comment]
Hey Folks, we've released middle-click paste support in today's release `[v0.2024.03.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.03.14-v0.2024.03.12.08.02)`.

Closing as resolved, but please let us know of any issues with the improvement.

**Comment by RicHincapie** [comment]
@dannyneira do I have to activate somewhere?
Warp version: v0.2024.03.12.08.02.stable_01
Ubuntu 22.04 LTS
Not working...

**Comment by dannyneira** [comment]
Thanks! Since Warp has a separate input/block list, plus other input areas like block filter and find, paste doesn't default to the input, but I see how that may be intuitive. We can certainly take this feedback onboard for possible improvement.

**Comment by SilentGlasses** [comment]
Thanks to the team for quickly pushing this feature out.  I am back to full working speed now.

**Comment by andersgb1** [comment]
> Thanks! Since Warp has a separate input/block list, plus other input areas like block filter and find, paste doesn't default to the input, but I see how that may be intuitive. We can certainly take this feedback onboard for possible improvement.

@dannyneira I second @RicHincapie's comment here, but still, super nice with the swift update! The extra detail, which saves and extra click each time, would make it super^2 nice :)

**Comment by SilentGlasses** [comment]
> @dannyneira do I have to activate it somewhere? Warp version: v0.2024.03.12.08.02.stable_01 Ubuntu 22.04 LTS Not working...
> 
> [UPDATE]
> 
> Its working if I select the text, click the terminal prompt, and hit middle click.
> 
> The original experience in Ubuntu terminal is not having to click in the prompt to get the middle click pasting there. It will always paste there.
> 
> Thanks for the upgrade, we're pretty close!

I did not have to. Maybe try exiting the app completely and starting a gain?

**Comment by andersgb1** [comment]
> > @dannyneira do I have to activate it somewhere? Warp version: v0.2024.03.12.08.02.stable_01 Ubuntu 22.04 LTS Not working...
> > [UPDATE]
> > Its working if I select the text, click the terminal prompt, and hit middle click.
> > The original experience in Ubuntu terminal is not having to click in the prompt to get the middle click pasting there. It will always paste there.
> > Thanks for the upgrade, we're pretty close!
> 
> I did not have to. Maybe try exiting the app completely and starting a gain?

Try clicking once on the "output" section above the input section at the bottom, then defocus and mark some text elsewhere, then you'll see a need for first clicking the input part and then middle-clicking before it pastes

**Comment by andersgb1** [comment]
Same actually if you just double click some text in the output section, then you defocus the input section, and you have to make two clicks to paste to the input...

**Comment by guy-borderless** [comment]
Hi, thanks for the feature! 

1.  I have some bugs with it 
2. in a split pane situation the focused pane should change IMO

here is a gif of the problem, you can see that middle click past is working well with vscode and chrome, but in warp there is what seems to be some cached value
![warpbug](https://github.com/warpdotdev/Warp/assets/100129659/b569e64b-d62c-4bab-8290-5d08b3ca9342)

you can see also that the pane I meant to paste to does no receive focus with the click

**Comment by alokedesai** [comment]
@andersgb1 Could you send a video of the issue with focus you're experiencing? I'd like to make sure I understand the issue so we can get it fixed 😄

**Comment by andersgb1** [comment]
Certainly! The video shows a session comparing gnome-terminal and Warp. The first time the middle-click works in both terminals, because the input section in Warp is "active" and ready for input. Around the 18s mark, I started interacting with the output section, causing the need for an extra left click in the input section at the bottom if I want to use middle-click.

Again, I don't know if this is even fixable, because it would require that middle-click both focuses back to the input section and pastes - but it would be nice to have :)

https://github.com/warpdotdev/Warp/assets/3854029/844d7f62-0790-4952-ba8a-42e38a569b08

**Comment by andersgb1** [comment]
OK just got an update to Warp, where this works! Nice work :clap:

**Comment by jeremyronking** [comment]
Did middle click paste stop working for anyone else with latest release?

v0.2024.03.12.08.02.stable_02
MacOS 14.2.1 (23C71)
MBP M1 Max

**Comment by alokedesai** [comment]
Hi @jeremyronking, we decided to make middle click paste linux-only for now. If you don't mind, feel free to create a new issue to track middle-click paste support on Mac (this issue is meant for Linux)

**Comment by jeremyronking** [comment]
> Hi @jeremyronking, we decided to make middle click paste linux-only for now. If you don't mind, feel free to create a new issue to track middle-click paste support on Mac (this issue is meant for Linux)

There was a ticket, but it was closed because of this fix. Perhaps you can reopen 
https://github.com/warpdotdev/Warp/issues/416

**Comment by alokedesai** [comment]
Done; I'll make sure to clarify that other one is Mac-specific.

**Comment by dannyneira** [comment]
thanks for calling that out @jeremyronking, I deleted my comment to avoid confusion.

**Comment by weirdan** [comment]
It looks like while middle-click now works for pasting into warp's input field, it still doesn't work for programs running in the warp window (e.g. an unsupported shell like nushell).

Steps to reproduce: 
* start nushell: `nu`
* output something: `ls`
* select something
* middle-click

Expected: the selected text is pasted
Actual: nothing happens

**Comment by alokedesai** [comment]
@weirdan Yes, that's correct. We're aware this is an issue and we're actively working on a fix for it.

**Comment by lordcris** [comment]
> OK just got an update to Warp, where this works! Nice work 👏

@andersgb1 Does it change focus back when you use middle-click with the new release? 
 Nothing has changed for me. I still need to first gain focus using the left click and than paste using the middle button.

**Comment by guy-borderless** [comment]
> > 
> Nothing has changed for me. I still need to first gain focus using the left click and than paste using the middle button.

me too

**Comment by andersgb1** [comment]
> > OK just got an update to Warp, where this works! Nice work 👏
> 
> @andersgb1 Does it change focus back when you use middle-click with the new release? Nothing has changed for me. I still need to first gain focus using the left click and then paste using the middle button.

No, it actually keeps the focus, wherever it is (input/output section), but the middle-click now always pastes into the input section, so I'm very happy here :)

**Comment by lordcris** [comment]
It doesn't work for me.
I still need to left click before using the middle click to paste.

**Comment by cgoerner** [comment]
Yep. Same here. With v0.2024.03.19.08.01.stable_01, middle-click doesn't automatically change the focus to the text input area for me.
Let me know if I can provide any system details.

**Comment by andersgb1** [comment]
@lordcris and @cgoerner , which OS are you on?

**Comment by lordcris** [comment]
> @lordcris and @cgoerner , which OS are you on?

```
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia
```

**Comment by cgoerner** [comment]
> @lordcris and @cgoerner , which OS are you on?

```
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```

**Comment by andersgb1** [comment]
OK @alokedesai , @cgoerner and @lordcris I also just realized that this only works "fully" when marking text in another app, and then middle-clicking into Warp.

When I try to do it within warp - e.g. mark part of a text in the output section - it again needs a left-click down in the input section before it does the paste upon middle-click. 

Even weirder, after having interacted with it for some time, trying middle-click both from other apps and the output section, I sometimes see "duplicate" pastes, i.e. the text I've marked in e.g. an external app gets pasted twice into the input field.

I can of course show another screencast, if needed.

**Comment by SilentGlasses** [comment]
Actually, it stopped working a bit after for me.  It worked for a bit after the update but then it just stopped.

My info:

Warp Version: v0.2024.03.19.08.01.stable_01

```
-----------------------
OS: Pop!_OS 22.04 LTS x86_64
Host: XPS 17 9710
Kernel: 6.6.10-76060610-generic
Uptime: 3 days, 17 hours, 4 mins
Packages: 1997 (dpkg), 33 (brew), 14 (flatpak)
Shell: zsh 5.8.1
Resolution: 5120x3200
DE: GNOME 42.5
WM: Mutter
WM Theme: Pop
Theme: Pop-dark [GTK2/3]
Icons: Pop [GTK2/3]
Terminal: WarpTerminal
CPU: 11th Gen Intel i9-11900H (16) @ 4.800GHz
GPU: Intel TigerLake-H GT1 [UHD Graphics]
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q
Memory: 18611MiB / 31825MiB
```

**Comment by abhishekp106** [comment]
> Even weirder, after having interacted with it for some time, trying middle-click both from other apps and the output section, I sometimes see "duplicate" pastes, i.e. the text I've marked in e.g. an external app gets pasted twice into the input field.

@andersgb1 Thanks for taking the time to file this issue! Could you send steps to reproduce this issue, or apps where this issue occurs? I reproduced it once by selecting in Firefox and then pasting in Warp, but can't get it to repro consistently.

**Comment by abhishekp106** [comment]
> When I try to do it within warp - e.g. mark part of a text in the output section - it again needs a left-click down in the input section before it does the paste upon middle-click.

@andersgb1 Working on a fix for this, so soon you won't need to focus the input editor for middle-click paste to work!

**Comment by andersgb1** [comment]
> > Even weirder, after having interacted with it for some time, trying middle-click both from other apps and the output section, I sometimes see "duplicate" pastes, i.e. the text I've marked in e.g. an external app gets pasted twice into the input field.
> 
> @andersgb1 Thanks for taking the time to comment! Could you send steps to reproduce this issue, or apps where this issue occurs? I reproduced it once by selecting in Firefox and then pasting in Warp, but can't get it to repro consistently.

Sorry, it's pretty difficult. The way I reproduced now was to:
- Open a new session
- List some files with the `ll` command
- Mark some of the output text from that command
- Single click to activate the input section (you're working on this to be easier, nice :+1:  ), middle-click to paste.
- Open a new gedit session, type some text
- Mark the text, middle-click anywhere in warp to paste.
- Go back to marking something new in the output section. Single-click plus middle-click to paste.
- Finally, mark the text in gedit again, middle-click to paste in Warp - sometimes needed a couple of times - and then it starts happening: I see the input pasted twice with each single middle-click.

Sorry again, there's likely much simpler instructions to repro, but this was what I could do for now.

**Comment by SilentGlasses** [comment]
This was working right after the initial change that enabled it. It worked for me both when middle clicking from withing Warp or from another app.  Not sure what changed after that but it seems to have broken after the last update for me.

**Comment by guy-borderless** [comment]
For me (manjaro Gnome) middle click still pastes to the keyboard-focused pane, even if the cursor is on top a different pane. for me expected behavior is that middle click over a certain pane will paste to that pane.

**Comment by lordcris** [comment]
From the latest changelog:

`Fixed an issue where users would need to focus the input editor before middle-clicking to paste`

unfortunately v0.2024.03.26.08.02.stable_02 didn't fix the bug for me. I still need to left click on the input editor before using the middle click to paste.

```
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia
```

**Comment by abhishekp106** [comment]
> From the latest changelog:
> 
> `Fixed an issue where users would need to focus the input editor before middle-clicking to paste`
> 
> unfortunately v0.2024.03.26.08.02.stable_02 didn't fix the bug for me. I still need to left click on the input editor before using the middle click to paste.
> 
> ```
> Distributor ID:	Linuxmint
> Description:	Linux Mint 21.3
> Release:	21.3
> Codename:	virginia
> ```

@lordcris Can you try middle-click to paste in the pane but not on top of the input editor? We're aware of an issue where middle-clicking on the input editor may not respond and will have it fixed in the next release. However, middle-clicking on an unfocused pane on any location beside the input editor should work now. Thanks for bearing with us as we iron out these issues.

**Comment by lordcris** [comment]
> @lordcris Can you try middle-click to paste in the pane but not on top of the input editor? We're aware of an issue where middle-clicking on the input editor may not respond and will have it fixed in the next release. However, middle-clicking on an unfocused pane on any location beside the input editor should work now. Thanks for bearing with us as we iron out these issues.

Yes, I just noticed that. If I'm pointing to a block different than the input editor it works. Thanks. I'll wait for the next release

**Comment by lordcris** [comment]
> > From the latest changelog:
> > `Fixed an issue where users would need to focus the input editor before middle-clicking to paste`
> > unfortunately v0.2024.03.26.08.02.stable_02 didn't fix the bug for me. I still need to left click on the input editor before using the middle click to paste.
> 
> @lordcris Can you try middle-click to paste in the pane but not on top of the input editor? We're aware of an issue where middle-clicking on the input editor may not respond and will have it fixed in the next release. However, middle-clicking on an unfocused pane on any location beside the input editor should work now. Thanks for bearing with us as we iron out these issues.


@abhishekp106 v0.2024.04.02.08.02.stable_01 fixes the issue for me. Now everything works as intended. Thank you!

**Comment by guy-borderless** [comment]
> > > From the latest changelog:
> > > `Fixed an issue where users would need to focus the input editor before middle-clicking to paste`
> > > unfortunately v0.2024.03.26.08.02.stable_02 didn't fix the bug for me. I still need to left click on the input editor before using the middle click to paste.
> > 
> > 
> > @lordcris Can you try middle-click to paste in the pane but not on top of the input editor? We're aware of an issue where middle-clicking on the input editor may not respond and will have it fixed in the next release. However, middle-clicking on an unfocused pane on any location beside the input editor should work now. Thanks for bearing with us as we iron out these issues.
> 
> @abhishekp106 v0.2024.04.02.08.02.stable_01 fixes the issue for me. Now everything works as intended. Thank 

for me too, although middle-clicking on the prompt ignores the paste

**Comment by abhishekp106** [comment]
> for me too, although middle-clicking on the prompt ignores the paste

@guy-borderless This will be fixed in the next release tomorrow!

**Comment by rameshsahoo111** [comment]
This is still not working on MAC.

**Comment by ablundgren** [comment]
> This is still not working on MAC.

This defect was specifically opened for Linux. Does MAC normally even have this feature in the UI?

**Comment by Gwondori** [comment]
It's not normal, but i need support on Mac too! iTerm (on Mac OS) also supports this functionality through its settings. I also used to be Linux, so I'm familiar with this feature :)

**Comment by Gwondori** [comment]
> > This is still not working on MAC.
> 
> This defect was specifically opened for Linux. Does MAC normally even have this feature in the UI?


It's not normal, but i need support on Mac too! iTerm (on Mac OS) also supports this functionality through its settings. I also used to be Linux, so I'm familiar with this feature :)

**Comment by jeremyronking** [comment]
> > This is still not working on MAC.
> 
> This defect was specifically opened for Linux. Does MAC normally even have this feature in the UI?

Yes this is a present feature in the OOTB terminal app shipped with Macs.  

Also, for those still wanting this fixed on Mac (like myself), please comment on https://github.com/warpdotdev/Warp/issues/416 as I was directed that this issue is specifically for Mac fix.

**Comment by roberte1342** [comment]
Adding my experience to this middle-click paste issue. I’m on Ubuntu 24.04 LTS, GNOME Shell 46.0, running Wayland (confirmed: $XDG_SESSION_TYPE=wayland). Warp version is v0.2025.02.19.08.02.stable_05. When I highlight text in another application (e.g., in Firefox) and middle-click in Warp’s input editor, it pastes my Clipboard (Ctrl+C’d earlier) instead of the highlighted Primary Selection. Steps:  

    Highlight ‘test’ in Firefox.  
    Middle-click Warp’s input area.  
    Get Clipboard content, not ‘test’.

In GNOME Terminal, middle-click pastes ‘test’ as expected, so it’s Warp-specific. ps -e shows Xwayland and gdm-wayland-ses, but no standalone Xorg, reinforcing Wayland.  Standard three-button mouse, no odd setup. Hope the Wayland detail helps—maybe a clipboard protocol mismatch? Thanks for all the fixes so far!

**Comment by SilentGlasses** [comment]
Hi there, this was closed out with no solution or any feedback if it's going to be looked into or not. This is a core feature I use daily that blocks me from using Warp as my main Terminal on Linux which is sad.  

Interestingly, I was asking the AI in Warp if it could help but I got this reply, I found solution 3 interesting:


> On Ubuntu, middle-click paste (also known as primary selection paste) might not be working in Warp due to how Warp handles clipboard management. This is a known behavior difference from traditional terminal emulators on Linux.
> 
> To enable middle-click paste in Warp on Ubuntu, you can try these solutions:
> 
> 1. Use the keyboard shortcut Shift + Insert instead, which is supported by Warp for pasting.
> 2. Use the standard copy-paste shortcuts:
> •  Copy: Ctrl + Shift + C
> •  Paste: Ctrl + Shift + V
> 
> If you specifically need middle-click paste functionality, you might want to:
> 1. Check if you have the latest version of Warp installed
> 2. Submit a feature request on Warp's GitHub repository if this functionality is important to you
> **3. Consider using a different terminal emulator that supports middle-click paste by default if this feature is critical for your workflow**
> 
> For now, it's recommended to use the keyboard shortcuts mentioned above as the primary way to paste content in Warp on Ubuntu.
