### ISSUE TITLE
Warp periodically stops responding to keyboard input

### ISSUE THREAD

**Issue by edmcman** [warpdotdev/Warp#4878]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

All Warp windows stop responding to keyboard input (at the same time).  If I type in any Warp window, no characters are echoed.  Hitting enter does not run the command, etc.  I can open new tabs or terminals and they have the same effect.  The windows are responsive to mouse clicks, however.  I can open the Warp settings and do other things via the mouse.

If I `killall -9 warp` I get this:
```
ed       1196362  9.2  0.5 15966196 501700 ?     Sl   May03 360:13  |   |       \_ x-terminal-emulator
ed       1196366  0.0  0.0      0     0 ?        Z    May03   0:00  |   |           \_ [warp] <defunct>
```

`x-terminal-emulator` is a symlink to `warp-terminal`.  If I `killall x-terminal-emulator`, all the warp terminals close, and if I restart warp, the terminal responds again.

### To reproduce

1. Leave a Warp terminal open for a while
2. Notice that it stops responding to keyboard input

Sorry, I don't know how to trigger this on demand.

### Expected behavior

I expected the terminal to remain responsive to keyboard input.

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.4 LTS

### Shell Version

fish, version 3.3.1

### Current Warp version

v0.2024.04.30.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by edmcman** [comment]
Also a bit strange (a few empty log files):
```
ls -lh
total 9.9M
-rw-rw-r-- 1 ed ed  52K May  6 08:37 warp.log
-rw-rw-r-- 1 ed ed  29K May  6 08:32 warp.log.old.0
-rw-rw-r-- 1 ed ed    0 May  6 08:27 warp.log.old.1
-rw-rw-r-- 1 ed ed    0 May  3 15:42 warp.log.old.2
-rw-rw-r-- 1 ed ed  17K May  3 12:50 warp.log.old.3
-rw-rw-r-- 1 ed ed    0 May  3 12:47 warp.log.old.4
-rw-rw-r-- 1 ed ed  22K May  6 08:35 warp_network.log
-rw-r--r-- 1 ed ed 8.3M May  6 08:32 warp.sqlite
-rw-r--r-- 1 ed ed  32K May  6 08:37 warp.sqlite-shm
-rw-r--r-- 1 ed ed 1.5M May  6 08:37 warp.sqlite-wal
```

**Comment by lstep** [comment]
I get the same problem, using Ubuntu 22.04.4 LTS. Everything works, display gets updated (seeing `htop` updating), mouse works fine, menus work fine, but no input at all possible from the keyboard, in any of the opened shells. Even if I open a new warp window, the keyboard input is blocked.
Only way I found to correct, is to kill all the processes and relaunch warp, which is a pain....

**Comment by dannyneira** [comment]
Hey folks, sorry about this. It's not clear what may be causing this if you could please provide the logs. https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs

**Comment by edmcman** [comment]
I am on vacation without my affected machine right now, so if someone else
could provide the logs that would be great. Otherwise I'll provide them as
soon as I get home.

**Comment by edmcman** [comment]
I'm back from vacation now.  I'll collect the logs the next time the problem occurs.

**Comment by edmcman** [comment]
[logs.zip](https://github.com/user-attachments/files/15615462/logs.zip)

**Comment by edmcman** [comment]
Let me know if I can provide anything else.  `warp.log` is empty for some reason.

**Comment by edmcman** [comment]
This is still happening very often.  I have to stop using warp until it's fixed.

**Comment by ToTheLaunchBay** [comment]
This is happening for me on EndeavourOS as well

**Comment by ToTheLaunchBay** [comment]
I just wanted to provide an update on this issue. It still happens for me on EndeavourOS, but a prior update seems to have made it easily fixable by clicking the title bar.

Basically, the terminal won't accept keyboard input until the title bar is clicked with the mouse

**Comment by edmcman** [comment]
I'm trying Warp again, and have not experienced the problem in the last ~24 hours.

**Comment by ToTheLaunchBay** [comment]
That's good to hear, Ed. Seems to be working 100% for me as well now. Maybe we can mark this one as resolved?

**Comment by edmcman** [comment]
Sure.  We can always reopen if there is a problem.

**Comment by dannyneira** [comment]
I'm reopening this as this issue has persisted intermittently for some users. Please report if you're seeing the problem and provide logs. https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs

**Comment by mfarley281** [comment]
Having this problem on kubuntu 24.04.2., logs attached 

[warp-logs.tar.gz](https://github.com/user-attachments/files/19526427/warp-logs.tar.gz)

**Comment by brendo-m** [comment]
Also seeing this I think, on MacOS 15.4.1. Slightly different - I can type characters, but enter does nothing. It happens within a few minutes of opening warp making it unusable

[warp-logs.zip](https://github.com/user-attachments/files/20844366/warp-logs.zip)

**Comment by edmcman** [comment]
> It is disappointing the amount of bugs I've started to need to work around with this terminal. I wish terminal UX was prioritized over all of these AI features that, I personally, am absolutely disinterested in.

👍 

I am not disinterested in AI features, and I've been using them on occasion.  But I definitely came here for a "modern" fast terminal.

**Comment by cavveman** [comment]
Was referred here from discord. I add my logs if it might help
[warp-logs.tar.gz](https://github.com/user-attachments/files/22987987/warp-logs.tar.gz)

**Comment by cavveman** [comment]
Check up your Qt installations. On my end it broke warp and some appimages. 
Got fixed with an update and reboot.

**Comment by edmcman** [comment]
Still happening on v0.2025.11.05.08.12.stable_00

I have stopped using warp for now... advanced features aren't that useful when you can't type anything

**Comment by mark-jordanovic-lewis** [comment]
In Ubuntu. Closing last tab of current window with `exit`. Warp window close process captures and closes keyboard input so no other warp windows can receive signals from keyboard.
