### ISSUE TITLE
Linux: Permanently showing `update warp` header, but there is no update

### ISSUE THREAD

**Issue by kubijo** [warpdotdev/Warp#5029]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The "Update Warp" header button is permanently shown, but there is apparently done.

### To reproduce

Nothing to do on user side

### Expected behavior

~~Up-to-date version does not show the header button.~~

It just (as of writing this) occurred to me to manually install the version from the web, and it got fixed.
I had `v0.2024.05.28.08.02.stable_00` and the web version was `v0.2024.06.11.08.02.stable_02`.

So perhaps the update / version checking process is broken.

### Operating system

Linux

### Operating system and version

Ubuntu 24.04 LTS (Noble Numbat)

### Shell Version

GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.05.28.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

---

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by yuvii** [comment]
happened to me too after upgrading from Ubuntu 23.10 to Ubuntu 24.04. The "upgrade warp" header just keeps showing up, clicking on it and running the command closes the terminal as if it has finished updating, then re-opens it and the header is still there

**Comment by kubijo** [comment]
Well ... I also did the upgrade, just haven't thought that it would be relevant info :)

**Comment by ibryans** [comment]
Same thing here, after updating ubuntu to 24.04. It keeps showing the "Update Warp" button to version v0.2024.06.11.08.02.stable_03

![image](https://github.com/warpdotdev/Warp/assets/28161519/e1b376bb-ecfa-4519-83e5-ecd49ab1d547)

**Comment by patmower** [comment]
Haven't checked yet, but I think it may be working.  I finally updated via the web site, and it seems to be loading my .bashrc file just fine.  Let me see about the next update.  
Thank you for all your hard work.

**Comment by dannyneira** [comment]
Hey folks, there was a newer version released for Linux `v0.2024.06.18.08.02.stable_04` Once that's installed it should resolve the update issue. Please let us know if it persists while on that version.

**Comment by ibryans** [comment]
Hey Danny, this newer version stable_04 really showed up, i tried to install it but it didn't work either. Now is showing a new version stable_01, but the update still doesn't work.

![image](https://github.com/warpdotdev/Warp/assets/28161519/b85074b8-a9b3-404f-8a03-7b8b26f849fe)

**Comment by dannyneira** [comment]
Hi folks,
Please run `cd /etc/apt/sources.list.d/ && ls`. I suspect the `warpdotdev.list` file in that folder gets renamed on an updating Ubuntu to `warpdotdev.list.distUpgrade` (or something similar). If so, then change it back with `sudo mv warpdotdev.list.distUpgrade warpdotdev.list`

please let us know if that helps with the issue.
