### ISSUE TITLE
Drag and Drop file pastes File Location 

### ISSUE THREAD

**Issue by relma2** [warpdotdev/Warp#5597]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

When I Drag and Drop a file from, say, Dolphin onto my Warp window, I want the file's location to be pasted where the text cursor was. <br /><span style="color:gray">*This works on other terminal emulators like Kitty.*</span>

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by heysweet** [comment]
Hello! I'm testing this locally on my Mac and we do seem to already support this (both in the terminal input field, and in interactive shell contexts like `vi`. Do you have any more context around when this isn't working for you?

**Comment by relma2** [comment]
I am on Linux

**Comment by heysweet** [comment]
Awesome, thanks for the context! It looks like we missed this with the initial Linux launch -- we'll prioritize launching this feature for Linux.

**Comment by relma2** [comment]
@heysweet Is this bug being worked on? I still can't drag-and-drop files

**Comment by nichoj10** [comment]
@relma2 If possible, can you share a video of what happens for you? This should be working on Linux

**Comment by relma2** [comment]
![Image](https://github.com/user-attachments/assets/1fac4131-eac0-405b-b461-fa8a5bccbbb1)

I'm on KDE Plasma 6, and using the Dolphin File Manager, I drag a md file into Warp and drop it and.... nothing.

Should I send you a log file?

**Comment by kimkimsh** [comment]
Still reproducing on Linux. Adding protocol-level evidence, since the last reply here said this should already be working on Linux.

## Environment

- Warp `v0.2026.08.26.17.59.stable.01` (.deb, `/opt/warpdotdev/warp-terminal/warp`)
- Ubuntu 24.04, GNOME Shell 46.0, **X11** session (`XDG_SESSION_TYPE=x11`) — so this is not Wayland-specific
- Drag sources tested: CLion 2026.2, Android Studio 2025.3.2, VS Code — all X11 clients
- Same drags into Tilix (VTE) insert the path correctly, so the sources are exporting `text/uri-list` fine

## What happens

Dragging a file or folder from the IDE project tree onto the Warp window does nothing at all: no path inserted at the cursor, no attachment, no visual feedback.

## The drop actually completes at the X11 protocol level

Immediately after dropping a folder from Android Studio onto the Warp window:

```
$ xprop -id 0x6600005   # WM_CLASS = "dev.warp.Warp"
XdndAware(ATOM) = BITMAP
XdndSelection(text/uri-list) = file:///home/<user>/workspace/<project>\r\n
```

Two things follow from that output:

1. Warp's window advertises `XdndAware` (atom `BITMAP` = 5, i.e. XDND v5), so it is a registered drop target.
2. The `text/uri-list` payload has been written into the `XdndSelection` property **on Warp's own window**. Under XDND, that only happens if the target issued `ConvertSelection` after `XdndDrop` — so the full `XdndEnter` → `XdndPosition` → `XdndDrop` → convert-selection handshake succeeded and the URI reached the Warp process.

The URI arrives and is then discarded.

## The binary already carries the winit DnD machinery

The atom names and the winit event names are present in the shipped binary (Rust interns these back-to-back in the string table, hence the run-on output):

```
$ strings -a /opt/warpdotdev/warp-terminal/warp | grep -o 'XdndAware[A-Za-z]*'
XdndAwareXdndEnterXdndLeaveXdndPositionXdndStatusXdndActionPrivateXdndSelectionXdndFinishedXdndTypeListtext

$ strings -a /opt/warpdotdev/warp-terminal/warp | grep -o 'HoveredFile[A-Za-z]*'
HoveredFileHoveredFileCancelledFocusedKeyboardInputImeCursorMovedCursorEnteredCursorLeftMouseWheelMouseInput...
```

So `WindowEvent::DroppedFile` is being produced at the windowing layer; what seems to be missing on Linux is the application-side handling that turns it into input insertion (or an attachment).

## No setting exists to enable it

```
$ warp dump-settings-schema | grep -ci 'drag\|drop'
0
```

(the dumped schema is ~131 KB; zero matches)

## Two small asks

1. This issue currently carries only the `os:windows` label, but it was reported on Linux and reproduces on Linux — `os:linux` would make it findable.
2. The Feb 2025 "this should be working on Linux" check may have been done on macOS. The evidence above suggests the Linux build never wires the `DroppedFile` event through.

Happy to provide a `RUST_LOG` trace or an `xev`/`xtrace` capture of the drop if that would help.
