### ISSUE TITLE
Issue with Warp’s Hotkey Mapping on macOS

### ISSUE THREAD

**Issue by laye95** [warpdotdev/Warp#5673]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

On my MacBook, I use Warp as my terminal. However, whenever I fully close Warp and reopen it, the dedicated hotkey for opening the Warp window no longer works. I have to manually remap the hotkey every time after reopening the application.

### To reproduce

1. Go to Settings -> Features -> Keys, enable Global hotkey and set a hotkey
2. Close warp fully
3. Reopen warp and try the hotkey.

### Expected behavior

That the hotkey keeps working after closing Warp

### Operating system

MacOS

### Operating system and version

15.2.0

### Current Warp version

v0.2025.01.08.08.02.stable_04

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by mallowigi** [comment]
+1 this was very unprecedented and affects me in my work. I'll be more aware to auto-update from now on

**Comment by pujayana** [comment]
I have the same issue :(

**Comment by laye95** [comment]
This one has been fixed. It is working as it should be again. So it can be closed.

**Comment by connorguy** [comment]
This is still an issue for me
- Warp v0.2025.02.12.16.51.stable_03
- MacOS 15.3 (24D60)

My hot key is option+backslash. Seems like the issue is intermittent.
