### ISSUE TITLE
Warp being flagged by antivirus

### ISSUE THREAD

**Issue by danielpeng2** [warpdotdev/Warp#5788]
### Dupe Check

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Tracking issue for issues related to antivirus software affecting usage of Warp.

### To reproduce

Try to run Warp while having an antivirus installed that flags Warp as a false positive.

### Operating system

Windows

### Operating system and version

Windows 11

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by danielpeng2** [comment]
If antivirus is affecting your usage of Warp, please let us know in the comments by providing:
- The operating system and version you're using
- Which antivirus is flagging Warp
- Any additional details the antivirus provides about Warp

**Comment by stojkovicv** [comment]
Hi, I am facing this very error on my machine:
- Windows 11
- Bitdefender
 ![Image](https://github.com/user-attachments/assets/246f790d-36c3-4e8d-b987-b116d349a6b1)

Translation: "A threat was found by the access scan. No configured actions could be performed, but access to the file was denied"

**Comment by kdoebel** [comment]
Same for me. 

Microsoft Windows 11 Pro
Version	10.0.26100 Build 26100

Bitdefender Version: 7.9.19.508

Error Messages are the same as for @stojkovicv.

**Comment by Maiz27** [comment]
Same here!

Windows 11 Home (23H2)
Verson 10.0.26100 Build 26100

Kaspersky Free (21.20.8.505)

![Image](https://github.com/user-attachments/assets/8e94d478-743b-4b5b-8c32-f8d9176778f0)

**Comment by danielpeng2** [comment]
@stojkovicv @kdoebel Did BitDefender give an error when you first installed Warp or did this only happen when you tried to update an existing installation of Warp?

**Comment by danielpeng2** [comment]
@Maiz27 Do you mind telling us which version of Warp you're using? You can find this if you right click on `warp.exe` and click on Properties -> Details. We pushed out an update a while ago that should've fixed problems with Kaspersky, so it'd be great to know if you're having issues on the latest version.

**Comment by kdoebel** [comment]
@danielpeng2 I tried to install Warp for the first time. 
My `warp.exe` was signed ‎26. ‎Feb ‎2025 04:38:36. Maybe that is helpful as well.

**Comment by Maiz27** [comment]
@danielpeng2 
File version 1.0.0.0
Product version v0.2025.02.24.20.50.stable_04

**Comment by stojkovicv** [comment]
@danielpeng2 More infos from Bitdefender, it treats it as the suspicious malware:


Malware Protection
March 5, 16:57

The access scan has detected a threat. No configured actions could be performed, but access to the file was denied.
`C:\Users\...\AppData\Local\Temp\is-R3J37.tmp\WarpSetup.tmp` is malware of the type Gen:Suspicious.Cloud.200.RVO@a08DTumi.

**Comment by dknight212** [comment]
![Image](https://github.com/user-attachments/assets/6042b05e-ebbb-4682-9137-2d954358fbc1)

![Image](https://github.com/user-attachments/assets/c703a5c4-f2f5-4b2e-9a51-559f32ebc484)

![Image](https://github.com/user-attachments/assets/8cae9d77-cafd-4d1a-be74-c8cd19bc3e24)

**Comment by stojkovicv** [comment]
Latest update: Installation is possible for Windows 11, but not execution:

![Image](https://github.com/user-attachments/assets/dec3689e-f3f4-4e36-91bc-b22708c81779)

@danielpeng2

**Comment by hasancemcerit** [comment]
Windows 11 Pro 25H2
Avast One

<img width="600" height="701" alt="Image" src="https://github.com/user-attachments/assets/914c6344-19cf-4eed-8063-066c21a3816c" />

<img width="600" height="573" alt="Image" src="https://github.com/user-attachments/assets/00e139c0-b902-42af-a9d9-f3b8016f2d9b" />

**Comment by dominicwild** [comment]
How are we doing with this? Kaspersky flagged and deleted this from my system still.

**Comment by NickWebsUS** [comment]
@dominicwild I think it's already been fixed in [#8794](https://github.com/warpdotdev/warp/issues/8794). Were you able to reinstall?

v0.2026.07.08.17.54.stable.02 [installers](https://www.warp.dev/download)

Not flagged:
WIN x64: https://www.virustotal.com/gui/file/687438271bb0d489855e09f978bfedfe859bdb26fd8a91e67bd1b728ad24f4fa
WIN ARM64: https://www.virustotal.com/gui/file/354eca981f376f8d7c08bba0c50538d062e3faf5f57e848f02a8de5e1ec83233
macOS: https://www.virustotal.com/gui/file/43d782779a23cb52c2ac38944f6e5c787ee11c09db4ef029b6228cb6cd8eede6
Linux .deb: https://www.virustotal.com/gui/file/7dd12fab8509cca750e827109a720f64440910a22c77b24094d11511e3569d30
Linux .rpm: https://www.virustotal.com/gui/file/5fd670c1cfc6b72b721d311f6691c87246b012044f97ec865e2c34425cdcfa69

**Comment by MatiasGaona** [comment]
<img width="1077" height="153" alt="Image" src="https://github.com/user-attachments/assets/88143a08-ecd9-49fe-ac61-5625f6d2226d" />
This is still happening; I have this version: v0.2026.09.02.08.27.stable_01. Before updating to that version, I didn't have any problems.
