### ISSUE TITLE
Path / File Tab Complete Awful

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#618]
### Describe the solution you'd like?

```shell
Let's say I'm in a folder with multiple files:

1. `CharlieTestFileA.txt`
2. `CharlieTestFileB.txt`
3. `CharlieTestFileC.txt`
4. etc...

I should be able to type `nano Char` then hit Tab.

Currently, Warp just shows a list of matching results. But this requires either hitting the arrow button a lot to find the result you are looking for or using the mouse.

In Terminal.app it pre-fills all identical text after what you typed which makes it **SUPER EASY** to continue to type and hit tab to autofill again. So in Terminal.app the same behavior would change my command to `nano CharlieTestFile` since that is the identical text for all files.

There is **NO** benefit to the user by not autofilling and changing the command to `nano CharlieTestFile`.
```

### Is your feature request related to a problem? Please describe.

```shell
Warp is awful when trying to autocomplete file/folder names. The whole user experience of allowing users to keep their hands on the keyboard and working fast is not possible with Warp.
```

**Comment by alokedesai** [comment]
Sorry for the issues Charlie! This is actually something we've already fixed and will launch in the next release tomorrow! We'll close it out tomorrow once it's launched

**Comment by fishcharlie** [comment]
@alokedesai Just updated and this seems to be working better, but still not great.

My original example wasn't good enough. Let's pretend I have the following directory structure.

<img width="139" alt="Screen Shot 2022-01-19 at 1 29 24 PM" src="https://user-images.githubusercontent.com/860375/150208742-0e6b537c-4e30-402e-9fc6-4c4e1c89a65b.png">

If I type `nano C` then hit Tab, it changes my command to `nano Charlie` which is great! If I then type `11` and hit tab again, all it does is go down to the next item on the list of autocomplete suggestions. It does **not** autofill in the `1_` part to make the entire command `nano Charlie111_`. However, I expect it to. Now if I hit Escape to make the autocomplete window disappear, and hit Tab again, it does autofill it again.

This leads to a situation where Tab means something **completely** different when the autocomplete view is open vs not. When it's open it just cycles through the results. When it's closed it autocompletes identical parts of the file for the prefix you entered, and opens the autocomplete view.

Having a key command mean two completely different things depending if a view is visible or not leads to a very bad UX.

Possibly this is related to #619??

I'd argue how this should work is that the Tab button **NEVER** cycles through the autocomplete choices, and instead it behaves identically to how it does if the autocomplete window is closed/hidden, autocompletes the remaining parts, and opens the autocomplete view (if multiple options exist).

For users that want to cycle through the autocomplete choices, they can still use the Arrow Down key. There is no reason in this instance to make both the Tab key and Arrow Down key bind to the same action.

---

I hope this makes sense, but if not I'd be happy to clarify anything as needed.

**Comment by elviskahoro** [comment]
@fishcharlie thanks for the feedback! Some great stuff here.

**Comment by dombarnes** [comment]
I've just switched form ohmyzsh to warp for  a while and one things its lacking on this front is partial name matching.

Example: I have 4 folders:
Folder.Hello
Folder.World
Folder.Baz
Folder.Foo

If I type `cd Foo` then tab, I'd expect `Folder.Foo` to be inserted or selectable, rather than needing to type `Folder.F` then tab
Ohmyzsh has no issues with this action.

**Comment by daKmoR** [comment]
not sure if a related issue... if I should open a new issue please let me know 🤗

I write `nvm` and it even gives me this nice preview of what it will do...
![Screenshot 2022-01-26 at 14 45 23](https://user-images.githubusercontent.com/24378/151174142-c514689d-3055-47ca-99c4-577bf0ca9d56.png)

so I hit "tab" but instead of completing it... I get this window

![Screenshot 2022-01-26 at 14 47 35](https://user-images.githubusercontent.com/24378/151174484-a06c703a-9405-41e8-bf5a-5c6eb9dc74e2.png)

if I want to complete it... I need to hit "Esc" and then arrow right (which means I will need to move my hand of my "writing  position")

**Comment by elviskahoro** [comment]
@daKmoR Thanks for the feedback. You don't need to make a new issue! There's just some UX we're working through!

**Comment by elviskahoro** [comment]
Added with v0.2022.02.21.08.55.stable_00
