### ISSUE TITLE
blank terminal when open microsoft edit

### ISSUE THREAD

**Issue by MiladSadeghi** [warpdotdev/Warp#6495]
### Pre-submit Checks

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates
- [x] I have [searched Warp known issues page](https://docs.warp.dev/help/known-issues) and my issue is not there
- [ ] I have included the logs (optional, but helps expedite the bug fix). [Log gathering intructions](https://docs.warp.dev/support-and-billing/sending-us-feedback#gathering-warp-logs)

### Describe the bug

The new file editor from Microsoft, called `edit`, doesn't work properly with Warp. When I try to open `edit` in Warp, it just shows a blank screen.

https://github.com/user-attachments/assets/c5f9a84a-3ac3-4f26-8f31-f40f90d192ae

### To reproduce

1. Install Microsoft's Edit (it's a standalone .exe and should be added to your system PATH).
2. Open Warp and type edit in the terminal.

### Expected behavior

`edit` should open in Warp like it does in a regular terminal (e.g., Windows Terminal).

https://github.com/user-attachments/assets/6c85acec-09ea-4302-acff-388bcace1c88

### Operating system (OS)

Windows

### Operating system and version

windows 11 24h2 26100.4061

### Current Warp version

v0.2025.05.14.08.11.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by ouariachi** [comment]
I have the same problem

**Comment by j4james** [comment]
@esafak The bug in ghostty that was preventing it from loading microsoft edit was fixed about a month ago. If you try the nightly build of ghostty it should work now.

**Comment by ninbura** [comment]
Still an issue as of October 2025 on the latest versions of Windows, Warp, and Microsoft Edit.
