### ISSUE TITLE
New update of Warp is crashing - Windows

### ISSUE THREAD

**Issue by nmoturi** [warpdotdev/Warp#6647]
### Pre-submit Checks

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates
- [x] I have [searched Warp known issues page](https://docs.warp.dev/help/known-issues) and my issue is not there
- [x] I have included the logs (optional, but helps expedite the bug fix). [Log gathering intructions](https://docs.warp.dev/support-and-billing/sending-us-feedback#gathering-warp-logs)

### Describe the bug

The new version of warp on windows platform is crashing.

### To reproduce

Open the warp terminal and type the command..it will crash

### Expected behavior

It shouldn't crash

### Operating system (OS)

Windows

### Operating system and version

windows 11

### Current Warp version

v0.2025.06.20.22.47.stable_05

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by excalith** [comment]
Experiencing a similar crash after 2.0 update. On my end, it even crashes when Warp is idle, without entering any command. Other terminals work without any issues.

**os:** `windows 11 10.0.26100 Build 26100`
**warp:** `0.2025.06.20.22.47.stable_07`
**pwsh:** `7.5.2`
**clink:** `1.7.20`
**starship:** `1.23.0`

**Comment by alokedesai** [comment]
Hi folks, really sorry for the issues here. We are actively pushing out a new version with a fix.

In the meantime, you can download last week's release here: http://releases.warp.dev/stable/v0.2025.06.18.08.11.stable_03/WarpSetup.exe

**Comment by excalith** [comment]
Thanks @alokedesai, if you need any further tests or info let me know. Cheers!

**Comment by alokedesai** [comment]
@excalith Could you please download this build and help verify that the issue is fixed? Thanks!
http://releases.warp.dev/stable/v0.2025.06.20.22.47.stable_08/WarpSetup.exe

**Comment by excalith** [comment]
@alokedesai `windows_stable_release` with tag `v0.2025.06.20.22.47.stable_08` still crashes just like my reports [here in this block](https://github.com/warpdotdev/Warp/issues/6647#issuecomment-3003635324)

<details>
<summary>Logs</summary>

```yaml
2025-06-25T16:26:29Z [INFO] Initializing crash reporting Some("windows_stable_release") with tag "v0.2025.06.20.22.47.stable_08"...
...
2025-06-25T16:26:32Z [INFO] Current version (v0.2025.06.20.22.47.stable_08) is ahead of version in channel versions(v0.2025.06.20.22.47.stable_07), not updating
...
2025-06-25T16:26:45Z [ERROR] thread 'notify-rs windows loop' panicked at 'path is expected to be under the root': C:\cargo\registry\src\index.crates.io-1949cf8c6b5b557f\ignore-0.4.23\src\gitignore.rs:229
   0: git_filter_source_repo
   1: git_filter_source_repo
   2: git_filter_source_repo
   3: onig_get_syntax
   4: onig_get_string_end_by_callout_args
   5: onig_get_string_end_by_callout_args
   6: onig_get_string_end_by_callout_args
   7: onig_get_string_end_by_callout_args
   8: tree_sitter_rust
   9: onig_get_string_end_by_callout_args
  10: onig_get_string_end_by_callout_args
  11: onig_get_syntax
  12: KiUserApcDispatcher
  13: ZwWaitForSingleObject
  14: WaitForSingleObjectEx
  15: onig_get_syntax
  16: onig_get_syntax
  17: onig_get_syntax
  18: onig_get_string_end_by_callout_args
  19: BaseThreadInitThunk
  20: RtlUserThreadStart

2025-06-25T16:26:45Z [ERROR] thread 'notify-rs windows loop' panicked at 'panic in a function that cannot unwind': library\core\src\panicking.rs:218
   0: git_filter_source_repo
   1: git_filter_source_repo
   2: git_filter_source_repo
   3: onig_get_syntax
   4: onig_get_string_end_by_callout_args
   5: onig_get_string_end_by_callout_args
   6: onig_get_string_end_by_callout_args
   7: onig_get_string_end_by_callout_args
   8: tree_sitter_rust
   9: tree_sitter_rust
  10: tree_sitter_rust
  11: onig_get_syntax
  12: _CxxFrameHandler3
  13: is_exception_typeof
  14: _C_specific_handler
  15: is_exception_typeof
  16: _CxxFrameHandler3
  17: _chkstk
  18: RtlUnwindEx
  19: _C_specific_handler
  20: is_exception_typeof
  21: is_exception_typeof
  22: is_exception_typeof
  23: _CxxFrameHandler3
  24: _chkstk
  25: RtlWow64GetCurrentCpuArea
  26: RtlRaiseException
  27: RaiseException
  28: CxxThrowException
  29: onig_get_syntax
  30: onig_get_string_end_by_callout_args
  31: onig_get_string_end_by_callout_args
  32: onig_get_string_end_by_callout_args
  33: onig_get_string_end_by_callout_args
  34: onig_get_string_end_by_callout_args
  35: tree_sitter_rust
  36: onig_get_string_end_by_callout_args
  37: onig_get_string_end_by_callout_args
  38: onig_get_syntax
  39: KiUserApcDispatcher
  40: ZwWaitForSingleObject
  41: WaitForSingleObjectEx
  42: onig_get_syntax
  43: onig_get_syntax
  44: onig_get_syntax
  45: onig_get_string_end_by_callout_args
  46: BaseThreadInitThunk
  47: RtlUserThreadStart
```
</details>

Here is the full log with some redacted project names (first time using word *redacted*, pretty cool)
[warp.log](https://github.com/user-attachments/files/20907616/warp.log)

**Comment by alokedesai** [comment]
Thx for confirming, looks like there are multiple ways for this bug to repro. Will have a fix out ASAP.

**Comment by TManITtech** [comment]
By me (version **v0.2025.06.20.22.47.stable_07**) it crashes after running a git command (like `git status`). 

From my event viewer: 

> Application: pwsh.exe
CoreCLR Version: 9.0.425.16305
.NET Version: 9.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Microsoft.PowerShell.Internal.VirtualTerminal.<>c.<ReadKey>b__40_0()
   at Microsoft.PowerShell.Internal.VirtualTerminal._TryIgnoreIOE[T](Func`1 f)
   at Microsoft.PowerShell.Internal.VirtualTerminal.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadOneOrMoreKeys()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKeyThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)


---

> Faulting application name: warp.exe, version: 1.0.0.0, time stamp: 0x685b38be
Faulting module name: warp.exe, version: 1.0.0.0, time stamp: 0x685b38be
Exception code: 0xc0000409
Fault offset: 0x0000000000f0e882
Faulting process id: 0x0xEE38
Faulting application start time: 0x0x1DBE5F3CE8B7053
Faulting application path: C:\Users\someuser\AppData\Local\Programs\Warp\warp.exe
Faulting module path: C:\Users\someuser\AppData\Local\Programs\Warp\warp.exe
Report Id: d247c2ba-6917-4ffa-9289-38bcf29af510
Faulting package full name: 
Faulting package-relative application ID: 

---

> Fault bucket 1813151560708070545, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

> Problem signature:
P1: warp.exe
P2: 1.0.0.0
P3: 685b38be
P4: warp.exe
P5: 1.0.0.0
P6: 685b38be
P7: 0000000000f0e882
P8: c0000409
P9: 0000000000000007
P10: 

> Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fe0df9ef-b505-42aa-8f04-5237e1a0e420.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6c2b3c7b-8ece-4e79-86a9-de34e30c522d.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.941e77c2-841a-4ead-9e97-2cb3083c7e34.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d9cb5c70-dd57-4afe-8d27-ad0686db78ab.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.03d65b73-7aff-4a80-bbf4-6c1f41f9c8d0.tmp.xml

> These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_warp.exe_be83378efd9d1b454688e8f550c44a37c41817_bd3b0894_09493c34-a826-4587-96b5-03e8eeda482d

> Analysis symbol: 
Rechecking for solution: 0
Report Id: d247c2ba-6917-4ffa-9289-38bcf29af510
Report Status: 268435456
Hashed bucket: 3e4d1d658e442c63f9299bbcebf31c91
Cab Guid: 0

**Comment by excalith** [comment]
@alokedesai hey there, the last week's version of `v0.2025.06.18.08.11.stable_03` from your url to the executable still crashes with the same stacktrace. I believe this issue is related to v2.0 of Warp, if possible can you please share pre-2.0 version instead?

**Comment by excalith** [comment]
Hello @alokedesai, the `v0.2025.07.02.08.36.stable_01` was working as expected, but latest version `v0.2025.07.02.08.36.stable_02` started to crash again, I can confirm that it again happens on watched directory updates such as file modifications etc.

Can you please add a page where we can download older verions as well? 

<details>

<summary>Warp Logs</summary>
```py
2025-07-04T07:33:27Z [ERROR] thread 'notify-rs windows loop' panicked at 'panic in a function that cannot unwind': library\core\src\panicking.rs:218
   0: git_filter_source_repo
   1: git_filter_source_repo
   2: git_filter_source_repo
   3: onig_get_syntax
   4: onig_get_syntax
   5: onig_get_syntax
   6: onig_get_syntax
   7: onig_get_syntax
   8: tree_sitter_rust
   9: tree_sitter_rust
  10: tree_sitter_rust
  11: onig_get_syntax
  12: _CxxFrameHandler3
  13: is_exception_typeof
  14: _C_specific_handler
  15: is_exception_typeof
  16: _CxxFrameHandler3
  17: _chkstk
  18: RtlUnwindEx
  19: _C_specific_handler
  20: is_exception_typeof
  21: is_exception_typeof
  22: is_exception_typeof
  23: _CxxFrameHandler3
  24: _chkstk
  25: RtlWow64GetCurrentCpuArea
  26: RtlRaiseException
  27: RaiseException
  28: CxxThrowException
  29: onig_get_syntax
  30: onig_get_syntax
  31: onig_get_syntax
  32: onig_get_syntax
  33: onig_get_syntax
  34: onig_get_syntax
  35: tree_sitter_rust
  36: onig_get_syntax
  37: onig_get_syntax
  38: onig_get_syntax
  39: onig_get_syntax
  40: KiUserApcDispatcher
  41: ZwWaitForSingleObject
  42: WaitForSingleObjectEx
  43: onig_get_syntax
  44: onig_get_syntax
  45: onig_get_syntax
  46: onig_get_syntax
  47: BaseThreadInitThunk
  48: RtlUserThreadStart
```
</details>

**Comment by alokedesai** [comment]
Hi all, I am very sorry for the issues here. Crashes like this are unacceptable and we'll make sure we fix this holistically going forward.

While folks are blocked, you can download the working version here:
http://releases.warp.dev/stable/v0.2025.06.25.08.12.stable_02/WarpSetup.exe

**Comment by lhughes222** [comment]
Had opened an issue https://github.com/warpdotdev/Warp/issues/6778# for this same issue.
My logs below:

2025-07-06T17:24:55Z [INFO] dispatching global action for workspace:save_app
2025-07-06T17:25:07Z [INFO] dispatching typed action: BlockTextSelect(Begin { point: BlockListPoint { row: Lines(OrderedFloat(263.14749479293823)), column: 220 }, side: Left, selection_type: Simple, position: Vector2F(<1781, 435>) })
2025-07-06T17:25:07Z [INFO] dispatching typed action: BlockSelect(MouseDown(None))
2025-07-06T17:25:07Z [INFO] dispatching typed action: CloseContextMenu
2025-07-06T17:25:07Z [INFO] dispatching typed action: HandleFocusChange
2025-07-06T17:25:07Z [INFO] active window changed: Some(WindowId(0))
2025-07-06T17:25:07Z [INFO] dispatching global action for root_view:update_quake_mode_state
2025-07-06T17:25:07Z [INFO] dispatching global action for workspace:save_app
2025-07-06T17:25:07Z [INFO] dispatching typed action: BlockTextSelect(End)
2025-07-06T17:25:08Z [INFO] dispatching typed action: BlockTextSelect(Begin { point: BlockListPoint { row: Lines(OrderedFloat(262.70999479293823)), column: 220 }, side: Right, selection_type: Simple, position: Vector2F(<1783, 428>) })
2025-07-06T17:25:08Z [INFO] dispatching typed action: BlockSelect(MouseDown(None))
2025-07-06T17:25:08Z [INFO] dispatching typed action: CloseContextMenu
2025-07-06T17:25:08Z [INFO] dispatching typed action: BlockTextSelect(End)
2025-07-06T17:25:08Z [INFO] dispatching typed action: TryAccept
2025-07-06T17:25:08Z [ERROR] thread 'notify-rs windows loop' panicked at 'path is expected to be under the root': C:\cargo\registry\src\index.crates.io-1949cf8c6b5b557f\ignore-0.4.23\src\gitignore.rs:229
0: git_filter_source_repo
1: git_filter_source_repo
2: git_filter_source_repo
3: onig_get_syntax
4: onig_get_syntax
5: onig_get_syntax
6: onig_get_syntax
7: onig_get_syntax
8: tree_sitter_rust
9: onig_get_syntax
10: onig_get_syntax
11: onig_get_syntax
12: onig_get_syntax
13: KiUserApcDispatcher
14: ZwWaitForSingleObject
15: WaitForSingleObjectEx
16: onig_get_syntax
17: onig_get_syntax
18: onig_get_syntax
19: onig_get_syntax
20: BaseThreadInitThunk
21: RtlUserThreadStart

2025-07-06T17:25:08Z [ERROR] thread 'notify-rs windows loop' panicked at 'panic in a function that cannot unwind': library\core\src\panicking.rs:218
0: git_filter_source_repo
1: git_filter_source_repo
2: git_filter_source_repo
3: onig_get_syntax
4: onig_get_syntax
5: onig_get_syntax
6: onig_get_syntax
7: onig_get_syntax
8: tree_sitter_rust
9: tree_sitter_rust
10: tree_sitter_rust
11: onig_get_syntax
12: _CxxFrameHandler3
13: is_exception_typeof
14: _C_specific_handler
15: is_exception_typeof
16: _CxxFrameHandler3
17: _chkstk
18: RtlUnwindEx
19: _C_specific_handler
20: is_exception_typeof
21: is_exception_typeof
22: is_exception_typeof
23: _CxxFrameHandler3
24: _chkstk
25: RtlWow64GetCurrentCpuArea
26: RtlRaiseException
27: RaiseException
28: CxxThrowException
29: onig_get_syntax
30: onig_get_syntax
31: onig_get_syntax
32: onig_get_syntax
33: onig_get_syntax
34: onig_get_syntax
35: tree_sitter_rust
36: onig_get_syntax
37: onig_get_syntax
38: onig_get_syntax
39: onig_get_syntax
40: KiUserApcDispatcher
41: ZwWaitForSingleObject
42: WaitForSingleObjectEx
43: onig_get_syntax
44: onig_get_syntax
45: onig_get_syntax
46: onig_get_syntax
47: BaseThreadInitThunk
48: RtlUserThreadStart

**Comment by alokedesai** [comment]
Hi all, deeply sorry for the issues here. The latest version of Warp should now have a fix for this. Please let me know if you're still experiencing issues.

Thanks!

**Comment by excalith** [comment]
Hey @alokedesai , just wanted to update you regarding my last comment:
I haven't experienced a single crash since the morning with the `v0.2025.07.02.08.36.stable_03` 🥳

**Comment by oauthentik** [comment]
sure @excalith , 

[warp.log](https://github.com/user-attachments/files/22391218/warp.log)
[warp_network.log](https://github.com/user-attachments/files/22391219/warp_network.log)
