### ISSUE TITLE
No prompt on SSH with starship

### ISSUE THREAD

**Issue by apfelbox** [warpdotdev/Warp#803]
### Describe the bug

```shell
I use [starship](https://starship.rs/) and when I access another machine via SSH, my prompt is just empty.
```

### To Reproduce

Steps to reproduce:
1. Use starship
2. `ssh ...`
3. Empty prompt

### Expected behaviour

```shell
I would like to have any shell. Not sure if starship works via ssh, but at least any shell would be great.
```

### Screenshots

![Capture 2022-03-10_18-28-51](https://user-images.githubusercontent.com/1032411/157720973-26d1a4dd-b92a-4b80-b2b1-e8b3e04511e9.png)

### Operating System

MacOS

### OS Version

12.2.1 (21D62)

**Comment by vorporeal** [comment]
Sorry about this!  Our custom prompt logic checks `$PS1`, but doesn't check the zsh synonym `$PROMPT`, which is what Starship uses.  I've got a basic fix in the works (to ensure you get _something_ to show up as the prompt), but it won't handle the right-side prompt text quite yet.

**Comment by apfelbox** [comment]
All right, thanks for the update.

I also get

```
manpath: can't set the locale; make sure $LC_* and $LANG are correct
bash: xxd: Command not found
```

via SSH.

`manpath` once on login and `xxd` every time:
![Capture 2022-03-22_20-19-57](https://user-images.githubusercontent.com/1032411/159558920-f4ebc422-bf9e-47b2-9272-7a6fac53e204.png)

**Comment by vorporeal** [comment]
Yeah, those seem to be separate issues.  I'm raising xxd being an insufficiently-standard binary with the team (any chance you're running Arch on the remote machine and don't have vim installed?) - you're not the first person who has run into issues with it.  The manpath locale error is new to me; I'll ask around.

**Comment by apfelbox** [comment]
I haven't set up this machine, but it appears that it is a "Rocky Linux 8.5 (Green Obsidian)".
`vim` is indeed not installed.

**Comment by elviskahoro** [comment]
Fixed!

**Comment by apfelbox** [comment]
I am on v0.2022.03.29.02.23.stable_01 and it's not yet fixed. When will it be included?

![Capture 2022-03-31_09-13-45](https://user-images.githubusercontent.com/1032411/160998801-9af04992-d8d1-4c46-ac76-6d9ea6a100cf.png)

**Comment by elviskahoro** [comment]
@apfelbox will flag this to team!

**Comment by vorporeal** [comment]
@apfelbox Sorry to hear it's not fixed for you yet; definitely playing a game of whack-a-mole with this one.

Would you mind sharing your .zshrc (and any other relevant shell initialization configuration)?  You can email it to me at david@warp.dev if you don't want to share it publicly, and feel free to/please remove any sensitive information/secrets.

**Comment by ahuth** [comment]
If it helps, I'm seeing the same issue (lack of any prompt). I'm:
- Using zsh on my host machine (Mac), and bash on the remote machine (Ubuntu)
- Warp is configured to honor the custom PS1 setting

On MacOS everything is working great.

**Comment by apfelbox** [comment]
@vorporeal thanks, just sent an email

**Comment by elviskahoro** [comment]
@ahuth @apfelbox Is this still broken?

**Comment by ahuth** [comment]
Can confirm it's fixed now. Thanks!

**Comment by apfelbox** [comment]
I have a prompt, but it seems pretty useless?

![CleanShot 2022-04-20 at 11 37 27](https://user-images.githubusercontent.com/1032411/164199149-228bef84-81c7-400f-b932-3d27ca0174dc.png)

Here is the comparison the Apples terminal:

![CleanShot 2022-04-20 at 11 38 04](https://user-images.githubusercontent.com/1032411/164199327-5639be9f-8d69-4630-ab76-5f807214d8e5.png)

**Comment by apfelbox** [comment]
@elviskahoro so I would say it's still broken (see above)

**Comment by elviskahoro** [comment]
Just an FYI: We still don't have support for right side prompts. @apfelbox we may need to work together on figuring out why it's not registering the same as mac terminal. Just to confirm does it still do this with the latest Warp version?

**Comment by elviskahoro** [comment]
@apfelbox please let me know if other things come up.
